/* eslint-disable prettier/prettier */

import { AssetLedgerSummary } from "./ledger";

/* prettier-ignore */
const testdata: AssetLedgerSummary[] = [
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1000000",
    "assetTypeName": "固定资产",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 13139440,
    "afterOriginalValue": 13140440,
    "beforeAccumulatedDepreciation": 1259604.67,
    "afterAccumulatedDepreciation": 1260604.67,
    "plusOriginalValue": 1000,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 1000,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "10",
    "assetTypeName": "房屋及构筑物",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 13058500,
    "afterOriginalValue": 13058500,
    "beforeAccumulatedDepreciation": 1240557.69,
    "afterAccumulatedDepreciation": 1240557.69,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "12",
    "assetTypeName": "车辆(大类)",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "13",
    "assetTypeName": "通用设备",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 71410,
    "afterOriginalValue": 72410,
    "beforeAccumulatedDepreciation": 18532.74,
    "afterAccumulatedDepreciation": 19532.74,
    "plusOriginalValue": 1000,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 1000,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "14",
    "assetTypeName": "专用设备",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "15",
    "assetTypeName": "文物和陈列品",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "16",
    "assetTypeName": "图书、档案(大类)",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 1000,
    "afterOriginalValue": 1000,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "17",
    "assetTypeName": "家具、用具、装具及动植物",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 8530,
    "afterOriginalValue": 8530,
    "beforeAccumulatedDepreciation": 514.24,
    "afterAccumulatedDepreciation": 514.24,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1393765520739840001",
    "assetTypeName": "无形资产大类",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 1000,
    "afterOriginalValue": 1000,
    "beforeAccumulatedDepreciation": 93.75,
    "afterAccumulatedDepreciation": 93.75,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3756",
    "assetTypeName": "土地大类",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3780",
    "assetTypeName": "专利权",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3771",
    "assetTypeName": "非专利技术",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3758",
    "assetTypeName": "商标权",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3760",
    "assetTypeName": "著作权",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "2640",
    "assetTypeName": "软件",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 1000,
    "afterOriginalValue": 1000,
    "beforeAccumulatedDepreciation": 93.75,
    "afterAccumulatedDepreciation": 93.75,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3766",
    "assetTypeName": "商誉",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3768",
    "assetTypeName": "其他",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "300000",
    "assetTypeName": "在建工程(大类)",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 12000,
    "afterOriginalValue": 12000,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3757",
    "assetTypeName": "在建工程(大类)",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 12000,
    "afterOriginalValue": 12000,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "400000",
    "assetTypeName": "长期股权投资",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "5",
    "assetTypeName": "长期股权投资",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "500000",
    "assetTypeName": "流动资产",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "3775",
    "assetTypeName": "流动资产",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "600000",
    "assetTypeName": "保障性住房",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496357725855746",
    "assetTypeName": "保障性住房",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "700000",
    "assetTypeName": "基础设施",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496358573105154",
    "assetTypeName": "交通公共基础设施",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496360447959041",
    "assetTypeName": "市政公共基础设施",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496368870121473",
    "assetTypeName": "水利公共基础设施",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1478567414876282882",
    "assetTypeName": "其他公共基础设施",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496375488733186",
    "assetTypeName": "政府储备物资",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496375681671170",
    "assetTypeName": "森林防火储备物资",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496378810621954",
    "assetTypeName": "防汛储备物资",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496380958105602",
    "assetTypeName": "自然灾害救助物资",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496381805355010",
    "assetTypeName": "城市排水防涝设备物资",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496384472932354",
    "assetTypeName": "应急储备物资",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496386339397633",
    "assetTypeName": "其他储备物资",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "800000",
    "assetTypeName": "文物文化",
    "isParent": true,
    "child": [],
    "init": true,
    "canClick": false,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  },
  {
    "belongId": "",
    "month": "",
    "assetTypeId": "1343496372078764033",
    "assetTypeName": "文物文化",
    "isParent": false,
    "child": [],
    "init": true,
    "canClick": true,
    "beforeOriginalValue": 0,
    "afterOriginalValue": 0,
    "beforeAccumulatedDepreciation": 0,
    "afterAccumulatedDepreciation": 0,
    "plusOriginalValue": 0,
    "minusOriginalValue": 0,
    "plusAccumulatedDepreciation": 0,
    "minusAccumulatedDepreciation": 0
  }
];

export default testdata;
